### PR TITLE
adds basic MIDI functionality

### PR DESCRIPTION
**Pull request by dqgorelick**
# Add basic midi functionality  

Very fun tool, and I love the write-up! I pulled some code I recycle between projects to add MIDI support. There is still some smart MIDI mapping to do, but for now the MIDI notes just correspond to the regionIndex.
 
Little video of my sending automated MIDI signals:
https://user-images.githubusercontent.com/9147241/125560263-cd1ce2d3-ad1e-467e-8c82-858e07e248ca.mp4

### CODE REVIEW

**Comment by dqgorelick** [comment]
Sending euclidian patterns with a tool called TidalCycles :) 

https://user-images.githubusercontent.com/9147241/125561468-ca14f665-3009-4df2-8b3f-46c43f288268.mp4

TidalCycles code: 

```
do  
  hush
  d1 $ slow 2 $ struct "1(2,8)" $ midinote "0" # sound "venn" + up "8"
  d2 $ slow 2 $ struct "1(1,8)" $ midinote "0" # sound "venn" + up "1"
  d3 $ slow 2 $ struct "1(2,8,1)" $ midinote "0" # sound "venn" + up "32"
  d4 $ slow 2 $ struct "1(1,8,3)" $ midinote "0" # sound "venn" + up "16"
  d5 $ slow 2 $ struct "1(3,8,5)" $ midinote "0" # sound "venn" + up "<20 80>"
  d6 $ slow 2 $ struct "1(1,8,5)" $ midinote "0" # sound "venn" + up "<3 21>"
```

**Comment by nhthn** [comment]
Awesome! Really appreciate the PR.

I just realized that I didn't have a license on the repo, which I just fixed. Are you alright with having your contribution licensed under MIT?

**Comment by dqgorelick** [comment]
It's a really fun project! The MIT license sounds good, thank you for adding that!

**Comment by nhthn** [comment]
Great. Thanks again for the PR!

**Pull request merged**
